Repository 9-1379/T3-R2-FE-Server, pull requests merged in 2024-03, with the labels that each got.

#1 [1.15.3] Vue 프로젝트 생성
  bhr/.gitignore
  bhr/README.md
  bhr/babel.config.js
  bhr/jsconfig.json
  bhr/package-lock.json
  bhr/package.json
  bhr/public/favicon.ico
  bhr/public/index.html
  bhr/src/App.vue
  bhr/src/assets/logo.png
  bhr/src/components/HelloWorld.vue
  bhr/src/main.js
  bhr/vue.config.js
Labels: merge

#6 [Modify]헬로우월드 코드 수정
  bhr/package-lock.json
  bhr/package.json
  bhr/src/components/HelloWorld.vue
  bhr/src/main.js
Labels: merge

#9 [Add] 직원 리스트 화면 추가
  bhr/babel.config.js
  bhr/package-lock.json
  bhr/public/index.html
  bhr/src/App.vue
  bhr/src/assets/team_logo.png
  bhr/src/components/EmpList.vue
  bhr/src/components/NewEmp.vue
  bhr/src/components/menu/AdminMenu.vue
  bhr/src/main.js
  bhr/src/main/resources/static/index.html
  bhr/src/main/resources/static/js/app.js
  bhr/src/main/resources/static/js/chunk-vendors.js
  bhr/src/router/index.js
Labels: help wanted, merge

#15 empid, empnum, 부서 목록 신규 직원 생성 창에서 보이도록 수정
  bhr/src/components/NewEmp.vue
Labels: merge

#12 [Add] 직원 상세 정보 ui
  bhr/src/assets/profile_basic.png
  bhr/src/components/EmpDetail.vue
  bhr/src/components/EmpList.vue
  bhr/src/components/emp_info/emp_reg.vue
  bhr/src/router/index.js
Labels: merge

#17 [Add] 관리자 메뉴바 ui
  bhr/package-lock.json
  bhr/package.json
  bhr/src/App.vue
  bhr/src/components/EmpDetail.vue
  bhr/src/components/EmpList.vue
  bhr/src/components/NewEmp.vue
  bhr/src/components/menu/AdminMenu.vue
  bhr/src/main.js
  bhr/src/store/store.js
Labels: merge

#16 [Feature]연차 신청 화면
  README.md
  bhr/package-lock.json
  bhr/src/components/NewAnnual.vue
  bhr/src/components/menu/AdminMenu.vue
  bhr/src/router/index.js
Labels: good first issue

#18 인사 카드 페이지
  bhr/src/axios.js
  bhr/src/components/emp/hrcard/EmployeeProfile.vue
  bhr/src/components/emp/hrcard/EmployeesList.vue
  bhr/src/components/emp/hrcard/HrCardMain.vue
  bhr/src/router/index.js
Labels: good first issue, merge

#23 [Modify] UI 왼쪽 정렬
  bhr/src/components/EmpDetail.vue
  bhr/src/components/EmpList.vue
  bhr/src/components/NewEmp.vue
  bhr/src/components/menu/AdminMenu.vue
Labels: merge
